### ISSUE TITLE
Not available in opam

### ISSUE THREAD

**Issue by mars0i** [ocaml-doc/odoc#77] opened 2017-05-12 21:55 UTC
Hi, I'm getting
```
~$ opam install odoc
Your request can't be satisfied:
  - No package matches odoc.

No solution found, exiting
```

After I got this message the first time, I tried doing an `opam update`, and then tried to install odoc again, but got the same message.  However, `opam update` gave this message, which I don't understand, but that I've been able to ignore in the past:

```
=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] synchronized from https://opam.ocaml.org
..The brute-force exploration algorithm timed-out [1183 states, 5s].
You might need to add explicit version constraints to your request to get a better answer.
```

**Comment by dbuenzli** [comment] 2017-05-12 22:23
Are you using the internal solver ? Please report the output of `opam config report`.

**Comment by mars0i** [comment] 2017-05-12 22:44
I guess this means that I am using the internal solver.  I don't really understand what an internal solver would be, and why I would want it.  I think I just have a default configuration.  I don't really understand external solvers either, but the concept makes sense to me.
```
~$ opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              darwin
# external-solver no
# criteria        -removed,-notuptodate,-changed
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.04.0
# last-update     2017-05-12 21:32
```

**Comment by dbuenzli** [comment] 2017-05-12 22:49
Well the internal solver is kind of a broken thing and `opam` is not really not usable with the large repo we have now. You should install an external solver otherwise you'll get into trouble all the time. I suspect you did not install `opam` via `brew` otherwise you would have gotten `aspcud`. So you can either 

1.  Install `opam` via `brew`
2. Try to install an external solver by yourself (`aspcud`)
3. Go the internal solver route but try to be more explicit in your opam requests by specifiying the version number i.e. `opam install odoc.1.0.0`. It may work or not.

**Comment by mars0i** [comment] 2017-05-12 23:03
OK, thanks very much.  Will work on this.  Not sure whether I used brew.  I have two machines, and I used it on one of them, but I don't know if I did on both.

**Comment by dbuenzli** [comment] 2017-05-12 23:05
I'm going to close this since it's not a bug. But feel free to continue the discussion if you need further help.

**Closed by dbuenzli** 2017-05-12 23:05 UTC
